FROM ubuntu:22.04

ARG DEBIAN_FRONTEND=noninteractive

ENV apt_update="apt-get update"
ENV apt_upgrade="apt-get upgrade -y"
ENV apt_install="apt-get install -y --no-install-recommends --no-install-suggests"
ENV pip_install="pip3 install --no-input"
ENV pip_upgrade="pip3 install --upgrade --no-input"

RUN $apt_update
RUN $apt_install apt-utils --no-install-recommends --no-install-suggests

RUN $apt_upgrade

# Install python
RUN $apt_install python3
RUN $apt_install python3-pip
RUN $pip_pgrade pip

# Install clang...
RUN $apt_install \
	clang-format \
	lld

RUN $apt_install gcc g++ gdb

RUN mv /usr/bin/ld /usr/bin/ld.unused
RUN ln -s /usr/bin/lld /usr/bin/ld

# Install build tools...
RUN $apt_install \
	cmake \
	ninja-build
	
# Install code analysis, testing, logging, and performance tools...
RUN $apt_install \
	valgrind \
	libgtest-dev \
	libgoogle-glog-dev \
	libbenchmark-dev \
	linux-tools-common \
	linux-tools-generic \
	strace \
	ltrace \
	lcov \
	gcovr

# Install additional high level libraries
RUN $apt_install \
	libboost-all-dev

# Install comm layers
RUN $apt_install \
	libzmq3-dev \
	libmosquitto-dev \
	mosquitto \
	mosquitto-clients \
	libmosquitto-dev

# Install some command-line tools
RUN $apt_install \
	git \
	vim \
	htop \
	tmux \
	socat \
	jpnevulator \
	net-tools

# Set some convenience options
RUN echo "set -g mouse on" > /root/.tmux.conf
RUN echo "set -o vi" > /root/.bashrc
RUN echo ":set tabstop=4" > /root/.vimrc
RUN echo ":set expandtab" >> /root/.vimrc
RUN echo ":set shiftwidth=4" >> /root/.vimrc
RUN echo ":set autoindent" >> /root/.vimrc
RUN echo ":set smartindent" >> /root/.vimrc
RUN echo ":set mouse=a" >> /root/.vimrc
RUN echo ":set number" >> /root/.vimrc
RUN echo ":set ruler" >> /root/.vimrc
